### ISSUE TITLE
Cannot build proton, appears wine-staging is missing

### ISSUE THREAD

**Issue by JooJooBee666** [Frogging-Family/wine-tkg-git#144] opened 2020-09-17 18:39 UTC
New to proton-tkg so cut me some slack.  I researched the issue but was unable to find the causes.  I can compile working 32 and 64 bit wine from staging manually without issue, so all dependencies are met.  I'm using KUbuntu 20.04.
When I run proton-tgk.sh, after the initial splash, i see the following:

`/build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer: line 27: cd: /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/src/wine-staging-git: No such file or directory
/build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer: line 33: cd: /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/src/wine-staging-git: No such file or directory
/build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer: line 39: cd: /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/src/wine-staging-git: No such file or directory
/build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer: line 45: cd: /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/src/wine-staging-git: No such file or directory
/build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer: line 51: cd: /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/src/wine-staging-git: No such file or directory
/build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer: line 67: cd: /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/src/wine-staging-git: No such file or directory
 ==> WARNING: HALP! We got some hotfixes for your current tree!
Do you want to apply them all with no further prompt?
> Y/n : ^C -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done`

This is on a clean clone of the repo.  I also confirmed that the /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/src/wine-staging-git is missing.  Not sure why that isn't being synced when I kick off the build script.

**Comment by Tk-Glitch** [comment] 2020-09-17 19:06
Thanks for your report!
Please run the `TkgThingy` script in the root of the PKGBUILDS repo then select the option 2 to update submodules then try running `proton-tkg.sh` again.

**Comment by JooJooBee666** [comment] 2020-09-17 19:11
Thanks.  I ran that and instead of just the 5 errors got around 100, and still no staging folder.  I can paste the whole thing if you'd like but it's long :)

**Comment by Tk-Glitch** [comment] 2020-09-18 11:01
Looks like you don't get git clones where you should. Can you please try running `non-makepkg-build.sh` from `PKGBUILDS/wine-tkg-git/wine-tkg-git/` and see if it's any different?
Also posting the full output (within a file or to pastebin for example) might help finding out what's going on,

**Comment by Tk-Glitch** [comment] 2020-09-18 11:19
Also, please attach your `prepare.log`, found in `PKGBUILDS/wine-tkg-git/wine-tkg-git/`as well.

**Comment by JooJooBee666** [comment] 2020-09-18 15:37
I was able to complete the build via `non-makepkg-build.sh` without incident.  This synced the wine-staging folder for me.  After that, I ran the `proton-tkg.sh` build script which then worked as expected.

Was I supposed to do that first?  I never saw that in the instructions anywhere and is there a risk it will break again?

**Comment by Tk-Glitch** [comment] 2020-09-18 16:34
I'd most definitely want to understand what happened :smile:  The proton-tkg script is supposed to call `non-makepkg-build.sh` so it's really weird.

**Comment by JooJooBee666** [comment] 2020-09-18 17:02
Ugh.  I'm so sorry about this.  I just figure out what it was. I completely forgot I replaced the `proton-tkg.cfg` with one supplied by someone else to get things compiled "correctly" for Microsoft Flight Simulator.  I just created yet another clone and was comparing when I caught it.  This was all my fault and I'm so sorry I wasted your time.  (－‸ლ) I'm sure it's safe to kill [ae3b9e92ce5dfa79c390312354a826e3a9d9f48c](https://github.com/Frogging-Family/wine-tkg-git/commit/ae3b9e92ce5dfa79c390312354a826e3a9d9f48c).

I attached the file if you want to look at it.  I know I'm going to have to make some changes to the default config (like changing the default version of windows) but I'm going to try and get a clean build first.

Just FYI, the base `proton-tkg.cfg` syncs the staging repo just fine.  I completed a new build with the default cfg but I still am not seeing anything in the `/.steam/root/compatibilitytools.d/`.  Should I open a new issue?

[proton-tkg.cfg.zip](https://github.com/Frogging-Family/wine-tkg-git/files/5246985/proton-tkg.cfg.zip)

Thanks for your patience @Tk-Glitch

**Comment by Tk-Glitch** [comment] 2020-09-18 17:13
Regarding the steam compat tools path, on *buntu it should be `"$HOME/.steam/compatibilitytools.d/"` (without the `root` part). The script *should* tell you the path used for installation at the end of the building process. If your proton-tkg build isn't found in there, then yes a new issue will be needed :smile: 

Thanks for the config file. I'm not seeing too exotic options in there at first glance, but if the default config worked for you, indeed it's probably related to something in there. I'll try to find the actual culprit with that.

You're very welcome, no worries :wink:

**Comment by JooJooBee666** [comment] 2020-09-18 18:45
Well, .root is just symlinked back to the .steam folder so both of those paths would work, but for sure not seeing anything in my steam folder.  I'll start a new issue and post the build log.  IT definitely does NOT say anything about the Steam path. :frowning_face:

**Comment by Tk-Glitch** [comment] 2020-09-18 18:59
You might be interested by this then: https://github.com/Tk-Glitch/PKGBUILDS/wiki/wine-tkg-git#dependencies
I thought Ubuntu fixed the SDL2 issue by now.. Looks like it's still a thing.

**Comment by JooJooBee666** [comment] 2020-09-18 19:05
Does it make sense that this only happens on the proton build?  The normal wine-tkg went fine.  I was able to confirm the build it made was complete and working.  I'll go ahead and try switching the packages around in the meantime.

**Comment by Tk-Glitch** [comment] 2020-10-29 19:23
I have since built proton-tkg multiple times on Ubuntu 20.04 and couldn't reproduce your initial issue. I'm closing this. I'll reopen in case the issue pops up again.

**Closed by Tk-Glitch** 2020-10-29 19:23 UTC
