### ISSUE TITLE
make: fatal error: stdlib.h: No such file or directory

### ISSUE THREAD

**Issue by shumvgolove** [Frogging-Family/wine-tkg-git#320] opened 2021-04-07 22:35 UTC
Arch Linux, everything's up to date.
```
In file included from /usr/include/c++/10.2.0/ext/string_conversions.h:41,
                 from /usr/include/c++/10.2.0/bits/basic_string.h:6535,
                 from /usr/include/c++/10.2.0/string:55,
                 from json/json.h:397,
                 from jsoncpp.cpp:76:
/usr/include/c++/10.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
winegcc: /usr/sbin/ccache failed
make: *** [Makefile:89: jsoncpp.o] Error 2
```

**Comment by Tk-Glitch** [comment] 2021-04-09 20:42
The issue is linked to the latest cmake update. I'm trying to find a workaround.

**Comment by Tk-Glitch** [comment] 2021-04-09 23:25
Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/7f48682fd6304780545c0b036b0dd01353521733

**Closed by Tk-Glitch** 2021-04-09 23:25 UTC
Labels: distro-related, upstream
