### ISSUE TITLE
Gamepad not working on any 6.0 builds

### ISSUE THREAD

**Issue by JooJooBee666** [Frogging-Family/wine-tkg-git#248] opened 2020-12-27 03:09 UTC
I can no longer see my gamepad on any of the 6.0 builds from the control panel and games don't recognise it either, same for both wired 360 controller and wireless Xbox one controller.  I can only see a disabled (js) device (see image).

![gamepad](https://user-images.githubusercontent.com/1514297/103163073-f554bc80-47c6-11eb-9900-fafeb21e6732.jpg)

I also tried the build you posted here (proton_tkg_6.0rc3.r0.g9912133b.release) but it has the same issue as well.  I recompiled with the "_gamepad_additions="true" flag, but this made no difference.  I can attach the log from the builds but seeing as the official release here is also broken, I see no point.  Maybe it's an issue with SDL?  Not really sure where to go from here.  Please let me know what else you need to troubleshoot this.

System:
Ubuntu 20.10
Kernel 5.8.0-33-generic

**Comment by Valmar33** [comment] 2020-12-27 03:23
Have you tried clicking on the disabled entry, and seeing if it becomes available to enable?

Just tried on my end ~ it defaults to not offering to enable, until I click on the entry proper, and then it gives me the choice to.

**Comment by JooJooBee666** [comment] 2020-12-27 03:30
I should have mentioned that.  Yes, but when I do it just disappears, it doesn't show up in the connected box, it's just GONE.  If I restart the control panel, it's back to disabled.

**Comment by JooJooBee666** [comment] 2020-12-27 04:13
Just to further clarify, the one that works correctly is just named "Xbox One Wireless Controller", which is missing now, no (js) appended.

**Comment by sonic2kk** [comment] 2020-12-28 04:09
Potentially related: #239, #231

**Comment by JooJooBee666** [comment] 2020-12-28 20:19
> Potentially related: #239, #231

Agreed.  I saw those too but I did a bit more digging and found it was for anything gamepad related.

Where upstream is this bug mentioned? Anyone know?  I don't see any patches at https://source.winehq.org/patches/ that seem to mention anything about gamepads, dinput, xinput or joysticks.

**Comment by Iglu47** [comment] 2021-01-14 19:03
I saw https://bugs.winehq.org/show_bug.cgi?id=50321#c1 and share here, sorry if not related

**Comment by logos128** [comment] 2021-01-14 20:57
The problem with controllers is caused by this commit [https://github.com/wine-mirror/wine/commit/e4fbae832c868e9fcf5a91c58255fe3f4ea1cb30](https://github.com/wine-mirror/wine/commit/e4fbae832c868e9fcf5a91c58255fe3f4ea1cb30). Haven't investigated it further, but my assumption is either it's causing the SDL2 to be not found on systems where SDL.h is located at the standard <SDL2/SDL.h> header location, or it's mixing SDL 1.xx with SDL 2 (???).

I am on Manjaro (Arch Linux) with both SDL 1.xx and SDL2 installed, and their headers are located respectively for SDL 1.xx at /usr/include/SDL/ , and for SDL2 at /usr/include/SDL2/. As this commit removes the SDL2 subpath when searching for SDL.h in the configure phase, it probably "assumes" there is no SDL support on the machine.

This affects only the proton builds which use SDL extensively for controller/gamepad support (proton or proton-tkg with "_sdl_joy_support" enabled). The wine, wine-staging, wine-tkg, etc., build's controller support is unaffected, so maybe this is one of the reasons why it stayed unnoticed at upstream.

Anyway, a quick fix for this is to revert the commit through "wine-tkg-userpatches". Just download the patch [https://github.com/wine-mirror/wine/commit/e4fbae832c868e9fcf5a91c58255fe3f4ea1cb30.patch](https://github.com/wine-mirror/wine/commit/e4fbae832c868e9fcf5a91c58255fe3f4ea1cb30.patch) and put it at "wine-tkg-git/wine-tkg-git/wine-tkg-userpatches/" with the extension ".myrevert". Then apply the revert when asked during the proton-tkg compilation.

IMO this must be reported upstream. I don't have an account at winehq.org, so if anyone with an account is willing to contribute, please report it there :)

**Comment by JooJooBee666** [comment] 2021-01-14 22:03
Confirmed.  Reverting this patch fixes the issue.  I guess my hunch about SDL was correct.

**Comment by Tk-Glitch** [comment] 2021-01-18 18:07
Should be fixed now. Closing.

**Closed by Tk-Glitch** 2021-01-18 18:07 UTC
Labels: bug, upstream

**Comment by JooJooBee666** [comment] 2021-01-18 18:09
Do I still need to revert or was this fixed upstream?

**Comment by JooJooBee666** [comment] 2021-01-18 18:12
Nevermind, I see what you did.  Thanks. 👍
