### ISSUE TITLE
(Proton) Rocket League will not launch at all

### ISSUE THREAD

**Issue by kescherCode** [Frogging-Family/wine-tkg-git#223] opened 2020-11-26 11:57 UTC
Neither the current release 9f4e86867cfc32b642acaa2bb9416c507abdd84e nor a self-built version from the current master branch 4b739742b1c38b35b1df18d46754dd749b77cda8 will allow me to launch Rocket League from within Steam. Attached is the very short proton log, which looks the same for both versions.

[steam-252950.log](https://github.com/Frogging-Family/wine-tkg-git/files/5602746/steam-252950.log)

The game works fine with Proton-5.21-GE-1 (not related to the current issue: A mod for Rocket League, BakkesMod, will currently hang on looking for a network adapter, causing me to revert to Proton-5.9-GE-8-ST) and Proton 5.13-2.
Additionally, other games (such as [Ascent](https://store.steampowered.com/app/1464000) or [Risk of Rain 2](https://store.steampowered.com/app/632360)) work fine with both builds of proton-tkg.

**Comment by kescherCode** [comment] 2020-11-26 12:32
Nevermind. A bunch of DLLs inside the Rocket League wineprefix were symlinked to the a removed Proton installation for some reason. I've removed the prefix and let Steam set up a new one.

The issue remains, however with a different log:

[steam-252950.log](https://github.com/Frogging-Family/wine-tkg-git/files/5602968/steam-252950.log)

**Comment by Tk-Glitch** [comment] 2020-11-26 14:33
I can't reproduce the issue on my end with r4. Possibly a regression affection r5, I'll check it out.
![Screenshot_20201126_152751](https://user-images.githubusercontent.com/741977/100363251-c0551e80-2ffc-11eb-9767-38519757a396.png)

**Comment by kescherCode** [comment] 2020-11-26 15:02
Definitely try with a fresh prefix, unlike my first try

**Comment by Tk-Glitch** [comment] 2020-11-26 15:25
I never installed the game before (ever), it was a fresh prefix.

**Comment by Tk-Glitch** [comment] 2020-11-27 15:29
I have since updated to r9 and it now refuses to run. Looks like an upstream regression so far.

**Comment by Tk-Glitch** [comment] 2020-12-05 13:11
![Screenshot_20201205_134559](https://user-images.githubusercontent.com/741977/101243521-465e1d00-3701-11eb-8c12-87db38243b30.png)
Tested again on a fresh prefix with a fresh build (proton_tkg_6.0rc1.r0.gd7b71f0b). The game is back to a working state. Closing.

**Closed by Tk-Glitch** 2020-12-05 13:11 UTC
