### ISSUE TITLE
Building latest wine-tkg-fsync fails

### ISSUE THREAD

**Issue by AlexanderWKoenig** [Frogging-Family/wine-tkg-git#1176] opened 2024-05-15 15:45 UTC
Hello,

having issues building latest wine-tkg since a week or so. 
Since your build server seems to build fine, I tried my luck and still running into this error:
```
../wine-git/server/device.c:855:9: Fehler: Implizite Deklaration der Funktion »close«; meinten Sie »pclose«? [-Wimplicit-function-declaration]
  855 |         close( manager->esync_fd );
      |         ^~~~~
      |         pclose
make: *** [Makefile:214458: server/device.o] Fehler 1
make: *** Es wird auf noch nicht beendete Prozesse gewartet …
../wine-git/server/esync.c: In Funktion »esync_dump«:
../wine-git/server/esync.c:152:34: Warnung: Format »%ld« erwartet Argumenttyp »long int«, aber Argument 3 hat Typ »int« [-Wformat=]
  152 |     fprintf( stderr, "esync fd=%ld\n", esync->fd );
      |                                ~~^     ~~~~~~~~~
      |                                  |          |
      |                                  long int   int
      |                                %d
../wine-git/server/esync.c: In Funktion »get_shm«:
../wine-git/server/esync.c:197:80: Warnung: Format »%ld« erwartet Argumenttyp »long int«, aber Argument 3 hat Typ »int« [-Wformat=]
  197 |             fprintf( stderr, "esync: couldn't expand shm_addrs array to size %ld\n", entry + 1 );
      |                                                                              ~~^     ~~~~~~~~~
      |                                                                                |           |
      |                                                                                long int    int
      |                                                                              %d
../wine-git/server/esync.c: In Funktion »esync_set_event«:
../wine-git/server/esync.c:405:50: Warnung: Format »%ld« erwartet Argumenttyp »long int«, aber Argument 3 hat Typ »int« [-Wformat=]
  405 |         fprintf( stderr, "esync_set_event() fd=%ld\n", esync->fd );
      |                                                ~~^     ~~~~~~~~~
      |                                                  |          |
      |                                                  long int   int
      |                                                %d
../wine-git/server/esync.c: In Funktion »esync_reset_event«:
../wine-git/server/esync.c:436:52: Warnung: Format »%ld« erwartet Argumenttyp »long int«, aber Argument 3 hat Typ »int« [-Wformat=]
  436 |         fprintf( stderr, "esync_reset_event() fd=%ld\n", esync->fd );
      |                                                  ~~^     ~~~~~~~~~
      |                                                    |          |
      |                                                    long int   int
      |                                                  %d
../wine-git/server/esync.c: In Funktion »esync_abandon_mutexes«:
../wine-git/server/esync.c:470:64: Warnung: Format »%ld« erwartet Argumenttyp »long int«, aber Argument 3 hat Typ »int« [-Wformat=]
  470 |                 fprintf( stderr, "esync_abandon_mutexes() fd=%ld\n", esync->fd );
      |                                                              ~~^     ~~~~~~~~~
      |                                                                |          |
      |                                                                long int   int
      |                                                              %d
../wine-git/server/event.c: In Funktion »event_destroy«:
../wine-git/server/event.c:302:9: Fehler: Implizite Deklaration der Funktion »close«; meinten Sie »pclose«? [-Wimplicit-function-declaration]
  302 |         close( event->esync_fd );
      |         ^~~~~
      |         pclose
make: *** [Makefile:214535: server/event.o] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
```

I've updated arch, run TkgThingy to update submodules and run makepkg like usual. `git status` says its clean. So dunno what I am doing wrong. Any hints?

[last_build_config.log](https://github.com/Frogging-Family/wine-tkg-git/files/15323960/last_build_config.log)
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/15323961/prepare.log)

**Comment by Nanotwerp** [comment] 2024-05-15 20:54
This is a duplicate of #1167 and #1170, an issue caused by GCC 14 being more strict with its errors. It's fixed, so use `git pull` and it'll compile.

**Comment by Tk-Glitch** [comment] 2024-05-15 21:23
Since you have a frogminer `wine-tkg.cfg`, you'll want to update your `_GCC_FLAGS` and `_CROSS_FLAGS` like this:
https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg#L43

**Comment by AlexanderWKoenig** [comment] 2024-05-15 22:14
> Since you have a frogminer `wine-tkg.cfg`, you'll want to update your `_GCC_FLAGS` and `_CROSS_FLAGS` like this: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg#L43

Yeah sounds logic. Will try tomorrow and will close this issue.

**Closed** 2024-05-15 22:25 UTC
Labels: config
