### ISSUE TITLE
ability to only use selected staging patches

### ISSUE THREAD

**Issue by r79** [Frogging-Family/wine-tkg-git#392] opened 2021-05-29 03:03 UTC
Fresh to the wine-building community. In order to get star citizen to run, it seems like one shouldn't use all of the staging patches, but only pick a bunch of them. I *could* download them all manually and pull them into the userpatches, but it would be much more convenient if there was some way to just have a config for them or something.

**Comment by Tk-Glitch** [comment] 2021-05-29 07:36
It's a recent regression. The simplest way right now is to drop staging altogether and make a mainline build.

There is actually a .cfg option to disable staging patchsets manually (staging userargs), but it can become a mess pretty fast since a staging patchset can depend on another, and the initial single patchset you wanted to disable might in fact force you to disable quite a few of them.

I am planning to add a specific toggle for star citizen soon so one can just turn it on to get a staging build that works with the game. The final goal is to get things fixed in staging so we can drop that option asap.

**Comment by r79** [comment] 2021-05-29 09:18
Yeah, I built it by just going mainline + throwing the staging patches needed into the custom folder, it's a bit of a mess but hey, it works. I don't think the SC community has yet determined proper Staging patchsets that would work, so I'm not sure if we'd be at a point where you could just make a lazy cfg option and be done :P

I'm personally getting more and more invested into fine-tuning things in order to boost the game some more, but hey, the current duct-tape solution is fine-ish for now for that purpose, and no matter what, I'm incredibly thankful for your work! <3

**Comment by Tk-Glitch** [comment] 2021-05-29 20:16
> I don't think the SC community has yet determined proper Staging patchsets that would work

I have. You just need to disable `ntdll-ForceBottomUpAlloc`, `ntdll-WRITECOPY` and `ntdll-Builtin_Prot`. You can do so by adding with `-W ntdll-ForceBottomUpAlloc -W ntdll-WRITECOPY -W ntdll-Builtin_Prot` to the `_staging_userargs` array in your .cfg.

**Comment by Tk-Glitch** [comment] 2021-05-29 20:47
I have added the necessary fluff with https://github.com/Frogging-Family/wine-tkg-git/commit/dc5e6dfadb15a9452d5e23859e00e7d6974d8835 and https://github.com/Frogging-Family/community-patches/commit/a0ebdee0cac236a6bcf3bfbc4a9434d1613a414a .

Now, when enabling `star-citizen-StorageDeviceSeekPenaltyProperty.mypatch` community patch on staging, the patchsets breaking the game will be disabled automatically :)

I guess I can close the issue. The way staging works makes it far too complex to take the "enabling on demand" route, but we're offering a "disabling on demand" way already, which imho makes more sense anyway. Please let me know if you feel like this issue needs to be re-opened.

**Closed by Tk-Glitch** 2021-05-29 20:47 UTC
