### ISSUE TITLE
Bioshock 1 & 2 crash on startup (works fine in upstream wine-staging)

### ISSUE THREAD

**Issue by IronSideSec** [Frogging-Family/wine-tkg-git#326] opened 2021-04-11 15:28 UTC
Hi, I've tried to play Bioshock 1 & 2 (both regular and remaster) using your wine-tkg (staging branch), unfortunately the app is crashing right after the bioshock logo shows up on the screen. It is however working fine when using regular wine-staging from arch repo. I have turned off esync and fsync as these games seem to not play well when enabled.

Error:

`
0024:fixme:ver:GetCurrentPackageId (0242FEF0 00000000): stub
0100:fixme:sync:SetWaitableTimerEx (0000014C, 02A4FB0C, 0, 00000000, 00000000, 00000000, 32) semi-stub
0164:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0164:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x4d6610, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0x1, mode_count 0x41fc30, modes (nil) partial stub!
0164:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x4d6610, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0x1, mode_count 0x41fc30, modes 0x21d2e410 partial stub!
0164:fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
0230:fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",457BFEC0): stub
0164:fixme:thread:SetThreadIdealProcessor (00000450 3): stub
0164:fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
0164:fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
0164:fixme:nvapi:unimplemented_stub function 0x2aede111 is unimplemented!
0164:fixme:d3d11:d3d11_device_CheckFeatureSupport Returning fake threading support data.
0164:fixme:dxgi:wined3d_swapchain_desc_from_dxgi Ignoring alpha mode 0.
0164:fixme:dxgi:wined3d_swapchain_desc_from_dxgi Unhandled mode scaling 0x2.
0164:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0xd9bd3a0, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0x1, mode_count 0x41d730, modes (nil) partial stub!
0164:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0xd9bd3a0, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0x1, mode_count 0x41d730, modes 0x21fe8d20 partial stub!
0164:fixme:dxgi:d3d11_swapchain_GetDesc Ignoring ScanlineOrdering and Scaling.
0164:fixme:dxgi:d3d11_swapchain_ResizeBuffers Ignoring flags 0x2.
0164:fixme:dxgi:dxgi_output_GetGammaControl iface 0xd9be220, gamma_control 0x53e6e7c stub!
0164:fixme:dxgi:dxgi_output_SetGammaControl Ignoring unhandled scale {0.00000000e+00, 0.00000000e+00, 0.00000000e+00}.
0164:err:xvidmode:ComputeGammaFromRamp low-biased gamma ramp (3277), rejected
0164:err:xvidmode:ComputeGammaFromRamp low-biased gamma ramp (3277), rejected
0164:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0164:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0164:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0164:fixme:dxgi:dxgi_output_SetGammaControl Ignoring unhandled scale {0.00000000e+00, 0.00000000e+00, 0.00000000e+00}.
0164:err:xvidmode:ComputeGammaFromRamp low-biased gamma ramp (3277), rejected
0164:err:xvidmode:ComputeGammaFromRamp low-biased gamma ramp (3277), rejected
0164:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0164:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0164:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0164:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0164:err:xvidmode:ComputeGammaFromRamp low-biased gamma ramp (3277), rejected
0164:fixme:thread:SetThreadIdealProcessor (00000480 2): stub
0164:fixme:thread:SetThreadIdealProcessor (0000048C 2): stub
0164:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0164:err:xvidmode:ComputeGammaFromRamp low-biased gamma ramp (2458), rejected
wine: Unhandled page fault on read access to 00000000 at address 10EF8413 (thread 0164), starting debugger...
`

I am also attaching a backtrace from the debugger. 
[backtrace.txt](https://github.com/Frogging-Family/wine-tkg-git/files/6292127/backtrace.txt)

My system info
OS:Arch linux
Kernel: 5.11.11-144-tkg-upds (also tried linux-zen "just in case")
GPU: AMD 5700XT running latest mesa-git drivers
Wine build: wine-6.5.r12.g64ea26c0 ( TkG Staging Esync Fsync )

**Comment by XaeroVincent** [comment] 2021-04-11 21:32
Do you have DXVK installed and being used in the game prefix?

**Comment by IronSideSec** [comment] 2021-04-12 07:14
> 
> 
> Do you have DXVK installed and being used in the game prefix?

Yes. I have tested this across different bottles (each time I tested new wine version I did a 'clean' install). with/without dxvk (from tkg repo), e/fsync. It does not start on the wine-tkg, but if I'd create a new bottle when using regular staging (following same steps to install dxvk) it runs as expected.

**Comment by IronSideSec** [comment] 2021-04-13 10:25
I've built the latest 6.6 staging from your repo now (config files were not changed, used defaults that are pulled from repo) and it of course failed to run the games, with same error.. Then I tried to run with your prebuilt package and.. it works...

**Comment by Tk-Glitch** [comment] 2021-04-13 15:49
Maybe a 6.6 regression. I'll give it a try on proton-tkg since there are a couple reverts there that might affect it. I might be worth porting those over if the issue is fixed with them.

**Comment by IronSideSec** [comment] 2021-04-13 17:07
Thanks, I'd appreciate some help here, while this is not a burning topic, and switching versions is not really a big deal (I could for once play a game from start to finish ;) ) if it could be avoided, it would be great :) If you need me to do anything, test etc, let me know, building the packages does not take that much so, happy to help :)

**Comment by Tk-Glitch** [comment] 2021-04-15 20:38
There might be a regression of some sort upstream if it used to work ootb. I have installed directx and vcrun2005 (both dependencies that the game ships with) and the game ran fine afterwards. That's on current HEAD of staging (6.6r6).
![Screenshot_20210415_223448](https://user-images.githubusercontent.com/741977/114935243-3ab2fd80-9e3b-11eb-9388-652d3face275.png)

**Closed** 2021-06-10 16:59 UTC
Labels: invalid
