### ISSUE TITLE
 Wine Ubuntu CI

### ISSUE THREAD

**Issue by rchris494** [Frogging-Family/wine-tkg-git#984] opened 2023-04-04 22:01 UTC
the wine ubuntu cl auto build seems to be failing

when i check the logs i see.

  -> ## Applying hotfix for plain-wine: Return_nt_filename_and_resolve_DOS_drive_path.mypatch
 -> ## Applying hotfix for plain-wine: ef6e33f.mypatch
 -> ## Applying hotfix for plain-wine: 0001-proton-bcrypt_rdr2_fixes5.mypatch
 -> ## Applying hotfix for plain-wine: 0002-bcrypt-Add-support-for-calculating-secret-ecc-keys.mypatch
 -> ## Applying hotfix for plain-wine: a608ef1.mypatch
 -> ## Applying hotfix for plain-wine: 1148-staging.mypatch
 ==> ERROR: Patch application has failed. The error was logged to /home/runner/work/wine-tkg-git/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
yes: standard output: Broken pipe
Error: Process completed with exit code 1.

would be be possible to get this fixed?

thanks

**Comment by csutcliff** [comment] 2023-04-04 22:13
duplicate of #979

**Comment by rchris494** [comment] 2023-04-05 02:26
duplicate problem

**Closed** 2023-04-05 02:26 UTC
