### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by psychaos999** [Frogging-Family/wine-tkg-git#295] opened 2021-03-04 22:45 UTC
Hi all,
on my rig, proton ge gives me a steady 60fps in elder scroll online
With Every proton tkg releases I'm lucky if I hit  30 fps, but more time then not fps are in the single digit and my SO became unresponsive
Proton tkg is used without any modification to user_setting.py
I dont know if it is of any help, but proton tkg has a really bad regression at least in eso

**Comment by Tk-Glitch** [comment] 2021-03-05 12:56
Sounds like futex2. If you have a kernel supporting futex2, try disabling it in user_setting.py. Some games/apps can lead to such results when using futex2, that's expected at this point in time.
I can't test teso but all games I have tested (disabling futex2 for the ones choking with it, similarly to your experience) are running perfectly fine as usual.

**Comment by psychaos999** [comment] 2021-03-09 05:45
Hi, and thank you for you efforts.
The problem persists even If I disable futex2.
Actually proton tkg has always been unplayable or worst performance wise against proton ge.

Dont take that as an advertising for proton ge. I really like to use your version, but  I played with almost any user_settings.py settings and had really bad performance. (xorg vs wayland could be a cause?)

Again thank you, and even if you wont take my issue into account, Id like to thank you from my hearth for what you are doing for the linux game comunity

**Comment by Tk-Glitch** [comment] 2021-03-09 14:43
The issue is there and I'll keep it open. If other people can confirm the issue I'm all ears.

What's your distro btw? Are you building proton-tkg yourself or are you using the prebuilts I push to github?

If you're using the prebuilts, it could very well be the gamepad additions (which are part of those builds but I keep that disabled for my own builds since all my gamepads are working perfectly fine without it). I have noticed that on - at least - Detroit: Become Human, that patchset leads to a very annoying cyclic stutters when my Dualshock 3 is plugged in. No issue with my Steam Controller though. Disabling the patchset and it's smooth sailing again. I can see the issue becoming worse with some other devices such as Corsair mice or some other gamepads.

> Dont take that as an advertising for proton ge. I really like to use your version, but I played with almost any user_settings.py settings and had really bad performance. (xorg vs wayland could be a cause?)

Well, Wine doesn't support Wayland (so you're stuck with XWayland) and the experience is always worse with it. Even if you can hit higher avg framerates in Wayland in *some* games as a benchmark, it's never as smooth as Xorg at this point in time and it can even be absolutely horrible with vsync enabled.
GE is using my patches for the most part with the main differences being that proton-tkg is built against system libs of whatever distro you're on (the prebuilts are built on Arch) while GE builds on Debian against Steam runtime and ships additional patched libs (that we don't need on an up to date Arch). That difference can change your experience quite a bit depending on your distro and its packages quality.
Since we're sharing the same patches it's extremely unlikely that your issue isn't either distro-related or configuration related as the part that runs your game - wine - is pretty much the same.

**Comment by psychaos999** [comment] 2021-03-15 19:55
Hi again,
sorry for the delay.

I'm using fedora rawhide. I'm playing only ESO and the performance difference between ge and tkg are too big, so I'm sure the problem is my system. Im using 5.11.5_tkg_upds+ kernel.

Would you say I'd be luckier to build tkg myself?

Thank you in advance and sorry for my bad english

**Comment by psychaos999** [comment] 2021-03-18 17:03
If I disable vkbasalt performance are on par with ge it seems

**Comment by Tk-Glitch** [comment] 2021-03-18 19:22
That means that due to your system configuration, the vulkan loader defaults to a different device (either an iGPU or lavapipe). That issue is known on the mesa side and happens since a wine update adding support for more vulkan functions in winevulkan, which might be missing from your ge build, or bypassed by the soldier runtime that we're not using in tkg.
There are multiple workarounds though, that may fix the issue with your specific machine, such as:
 - passing the `NODEVICE_SELECT=1` env var
 - setting the correct path for the driver's .json you want to use with the `VK_ICD_FILENAMES` env var
 - moving to mesa-git

**Comment by Tk-Glitch** [comment] 2021-05-15 13:58
Closing since it's not our issue

**Closed by Tk-Glitch** 2021-05-15 13:58 UTC
Labels: invalid
