### ISSUE TITLE
Error while creating ./config.status

### ISSUE THREAD

**Issue by MatMSantos** [Frogging-Family/wine-tkg-git#262] opened 2021-01-14 04:57 UTC
Apparently there is a syntax error when creating ./config.status:

![image](https://user-images.githubusercontent.com/68665056/104546784-b8345b00-560b-11eb-81be-9ff1365f0182.png)

**Comment by Tk-Glitch** [comment] 2021-01-19 17:00
This error is not generated by our scripts, it's on wine's side. However, I'm unable to reproduce this on my end and can't remember ever seeing this before. I'd try nuking your current tree and recloning freshly.

**Comment by Tk-Glitch** [comment] 2021-06-10 17:06
Hopefully fixed by now.

Closing

**Closed by Tk-Glitch** 2021-06-10 17:06 UTC
