### ISSUE TITLE
Cannot builkd Proton, missing Wine-Staging - Again

### ISSUE THREAD

**Issue by JooJooBee666** [Frogging-Family/wine-tkg-git#145] opened 2020-09-17 20:53 UTC
Again, new to proton-tkg so cut me some slack. My other issue was closed before verifying it was actually resolved.  I'm assuming you wanted another issue opened?

I researched the issue but was unable to find the causes. I can compile working 32 and 64 bit wine from staging manually without issue, so all dependencies are met. I'm using KUbuntu 20.04.
I ran TkgThingy and ensured all submodules were update.  However, when I run proton-tgk.sh, after the initial splash, i see the about 100 or so related errors to wine-staging-git missing, followed by:

`/build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer: line 402: cd: /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/src/wine-staging-git: No such file or directory`
` -> Hotfixing...`
` -> ## Applying hotfix for wine-mainline: 001-3a9edf9aad43c3e8ba724571da5381f821f1dc56.myearlypatch`
` -> ## Applying hotfix for wine-mainline: 002-e0e3b6bc91f7db956e3a66f2938eea45d4055a39.myearlypatch`
` -> ## Applying hotfix for wine-mainline: 003-1e7378d8-447bce41.myearlypatch`
`/build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/wine-tkg-scripts/prepare.sh: line 652: cd: /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/src/wine-staging-git: No such file or directory`
` -> Removed BIG_UGLY_FROGMINER - Ribbit`
` -> Removed Proton-tkg token - Valve Ribbit`
` -> exit cleanup done`

This is on a clean clone of the repo. I also confirmed that the /build/source/PKGBUILDS/wine-tkg-git/wine-tkg-git/src/wine-staging-git is still missing.

**Comment by Tk-Glitch** [comment] 2020-09-18 11:23
It's more a case of *this issue doesn't make sense* than anything. I can't reproduce it and you're the first buntu user facing this ever. Sorry for assuming it was the earlyhotfixer as it turns out it wasn't (and there was actually nothing wrong with it, even.
I have reopened https://github.com/Frogging-Family/wine-tkg-git/issues/144 and asked for a few things to figure out what's wrong here. Closing this so we can continue in https://github.com/Frogging-Family/wine-tkg-git/issues/144

**Closed by Tk-Glitch** 2020-09-18 11:23 UTC
