### ISSUE TITLE
merge conflict in dlls/winex11.drv/display.c (used non-makepkg-build.sh)

### ISSUE THREAD

**Issue by core36** [Frogging-Family/wine-tkg-git#609] opened 2021-12-01 09:41 UTC
I didn't have this problem yesterday using the same configuration.

terminal output: (i'm sorry, i speak german, my OS is set to german so the output is german too)

`
./non-makepkg-build.sh 
 -> Non-makepkg build script will be used.

 ->        .---.`               `.---.
 ->     `/syhhhyso-           -osyhhhys/`
 ->    .syNMdhNNhss/``.---.``/sshNNhdMNys.
 ->    +sdMh.`+MNsssssssssssssssNM+`.hMds+
 ->    :syNNdhNNhssssssssssssssshNNhdNNys:
 ->     /ssyhhhysssssssssssssssssyhhhyss/
 ->     .ossssssssssssssssssssssssssssso.
 ->    :sssssssssssssssssssssssssssssssss:
 ->   /sssssssssssssssssssssssssssssssssss/
 ->  :sssssssssssssoosssssssoosssssssssssss:
 ->  osssssssssssssoosssssssoossssssssssssso
 ->  osssssssssssyyyyhhhhhhhyyyyssssssssssso
 ->  /yyyyyyhhdmmmmNNNNNNNNNNNmmmmdhhyyyyyy/
 ->   smmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmms
 ->    /dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd/
 ->     `:sdNNNNNNNNNNNNNNNNNNNNNNNNNds:`
 ->        `-+shdNNNNNNNNNNNNNNNdhs+-`
 ->              `.-:///////:-.`
 -> 
 -> #################################################################
 -> 
 -> You can configure your wine build flavour (right now for example)
 -> by editing the customization.cfg file next to this PKGBUILD,
 -> or by creating a custom config, for example
 -> ~/.config/frogminer/wine-tkg.cfg (path set in config file)
 -> to override some or all of its values.
 -> 
 -> Current path is '/home/taube/GITs/customWine/wine-tkg-git/wine-tkg-git'
 -> 
 -> If you are rebuilding using the same configuration, you may want
 -> to delete/move previously built package if in the same dir.
 -> 
 -> ###################################TkG##########was##########here
When you are ready, press enter to continue.
 -> Using staging patchset
 -> Using fsync patchset
 -> Using pba patchset
 -> Cloning and preparing sources... Please be patient.
 -> Cleaning wine-staging source code tree...
 -> Cleaning wine source code tree...
 ==> WARNING: ! Staging has disabled mfplat support on this revision, so video playback will not work in games using mfplat !
 -> Changing wine HEAD to the wine-staging base commit...
Hinweis: Wechsle zu 'c0ea1ad37d3343c403d80ee18bf0d90c2699148b'.

Sie befinden sich im Zustand eines 'losgelösten HEAD'. Sie können sich
umschauen, experimentelle Änderungen vornehmen und diese committen, und
Sie können alle möglichen Commits, die Sie in diesem Zustand machen,
ohne Auswirkungen auf irgendeinen Branch verwerfen, indem Sie zu einem
anderen Branch wechseln.

Wenn Sie einen neuen Branch erstellen möchten, um Ihre erstellten Commits
zu behalten, können Sie das (jetzt oder später) durch Nutzung von
'switch' mit der Option -c tun. Beispiel:

  git switch -c <neuer-Branchname>

Oder um diese Operation rückgängig zu machen:
  git switch -

Sie können diesen Hinweis ausschalten, indem Sie die Konfigurationsvariable
'advice.detachedHead' auf 'false' setzen.

HEAD ist jetzt bei c0ea1ad37d3 msvcr100: Add _Timer class implementation.
 ==> WARNING: Hotfix: Staging's mfplat support patchset is currently disabled, breaking video playback in various games
  Restore it?
> N/y : y
 ==> WARNING: Hotfix: Restore staging's mfplat support patchset
 ==> WARNING: Hotfix: Fix for Riot Client updates
 ==> WARNING: Hotfix: Revert Quartz changes breaking Tokyo Xanadu Xe+
 ==> WARNING: Hotfix: Bcrypt fixes for RDR2
 ==> WARNING: Hotfix: Staging's winepulse pulseaudio support patchset is currently disabled, leading to audio skips and crackling in various games.
  Restore it?
> N/y : y
 ==> WARNING: Hotfix: Restore staging's winepulse pulsaudio support patchset - Fixes audio skips and crackling in various games
 ==> WARNING: Hotfix: Protonify staging syscall emu
 ==> WARNING: Hotfix: Revert bd27af97 to fix many game launchers displaying empty windows (StarCitizen, EGS, Riot Client, Minecraft Dungeons etc.)
 ==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
 -> Hotfixing...
error: Konnte "revert" nicht auf 2adf4376d86... (winex11.drv: Pass size in bytes to RegQueryValueExW().) ausführen
Hinweis: nach Auflösung der Konflikte markieren Sie die korrigierten Pfade
Hinweis: mit 'git add <Pfade>' oder 'git rm <Pfade>'
 ==> ERROR: Patch application has failed. The error was logged to /home/taube/GITs/customWine/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
 -> To use the last known good mainline version, please set _plain_version="" in your .cfg
 -> To use the last known good staging version, please set _staging_version="" in your .cfg (requires _use_staging="true")
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
taube@taube-P65-67RSRP:~/GITs/customWine/wine-tkg-git/wine-tkg-git$ cat /home/taube/GITs/customWine/wine-tkg-git/wine-tkg-git/prepare.log
Klone in Bare-Repository 'wine-mirror-git' ...
Klone in Bare-Repository 'wine-staging-git' ...
Fordere an von origin
Klone nach '/home/taube/GITs/customWine/wine-tkg-git/wine-tkg-git/src/wine-staging-git' ...
Fertig.
Zu neuem Branch 'makepkg' gewechselt
Fordere an von origin
Klone nach '/home/taube/GITs/customWine/wine-tkg-git/wine-tkg-git/src/wine-mirror-git' ...
Fertig.
Aktualisiere Dateien: 100% (9178/9178), fertig.
Zu neuem Branch 'makepkg' gewechselt
HEAD ist jetzt bei 4c51f4f5 Rebase against c0ea1ad37d3343c403d80ee18bf0d90c2699148b.
HEAD ist jetzt bei c0ea1ad37d3 msvcr100: Add _Timer class implementation.

747905c674d521b61923a6cff1d630c85a74d065 reverted (hotfix)

f3624e2d642c4f5c1042d24a70273db4437fcef9 reverted (hotfix)

769057b9b281eaaba7ee438dedb7f922b0903472 reverted (hotfix)

639c04a5b4e1ffd1d8328f60af998185a04d0c50 reverted (hotfix)

54f825d237c1dcb0774fd3e3f4cfafb7c243aab5 reverted (hotfix)

cad38401bf091917396b24ad9c92091760cc696f reverted (hotfix)

894e0712459ec2d48b1298724776134d2a966f66 reverted (hotfix)

42da77bbcfeae16b5f138ad3f2a3e3030ae0844b reverted (hotfix)

2f7e7d284bddd27d98a17beca4da0b6525d72913 reverted (hotfix)

f4b3eb7efbe1d433d7dcf850430f99f0f0066347 reverted (hotfix)

72b3cb68a702284122a16cbcdd87a621c29bb7a8 reverted (hotfix)

a1a51f54dcb3863f9accfbf8c261407794d2bd13 reverted (hotfix)

3e0a9877eafef1f484987126cd453cc36cfdeb42 reverted (hotfix)

5d0858ee9887ef5b99e09912d4379880979ab974 reverted (hotfix)

d1662e4beb4c1b757423c71107f7ec115ade19f5 reverted (hotfix)
automatischer Merge von dlls/mf/tests/mf.c

dab54bd849cd9f109d1a9d16cb171eddec39f2a1 reverted (hotfix)
automatischer Merge von dlls/mf/tests/mf.c

3864d2355493cbadedf59f0c2ee7ad7a306fad5a reverted (hotfix)

fca2f6c12b187763eaae23ed4932d6d049a469c3 reverted (hotfix)

63fb4d8270d1db7a0034100db550f54e8d9859f1 reverted (hotfix)

25adac6ede88d835110be20de0164d28c2187977 reverted (hotfix)

dc1a1ae450f1119b1f5714ed99b6049343676293 reverted (hotfix)

aafbbdb8bcc9b668008038dc6fcfba028c4cc6f6 reverted (hotfix)

682093d0bdc24a55fcde37ca4f9cc9ed46c3c7df reverted (hotfix)

21dc092b910f80616242761a00d8cdab2f8aa7bd reverted (hotfix)

d7175e265537ffd24dbf8fd3bcaaa1764db03e13 reverted (hotfix)

5306d0ff3c95e7b9b1c77fa2bb30b420d07879f7 reverted (hotfix)

00bc5eb73b95cbfe404fe18e1d0aadacc8ab4662 reverted (hotfix)

a855591fd29f1f47947459f8710b580a4f90ce3a reverted (hotfix)

34d85311f33335d2babff3983bb96fb0ce9bae5b reverted (hotfix)

42c82012c7ac992a98930011647482fc94c63a87 reverted (hotfix)

4398e8aba2d2c96ee209f59658c2aa6caf26687a reverted (hotfix)

c9f5903e5a315989d03d48e4a53291be48fd8d89 reverted (hotfix)

56dde41b6d91c589d861dca5d50ffa9f607da1db reverted (hotfix)

c3811e84617e409875957b3d0b43fc5be91f01f6 reverted (hotfix)

799c7704e8877fe2ee73391f9f2b8d39e222b8d5 reverted (hotfix)

399ccc032750e2658526fc70fa0bfee7995597df reverted (hotfix)

f7b45d419f94a6168e3d9a97fb2df21f448446f1 reverted (hotfix)

6cb1d1ec4ffa77bbc2223703b93033bd86730a60 reverted (hotfix)

7c02cd8cf8e1b97df8f8bfddfeba68d7c7b4f820 reverted (hotfix)

6f8d366b57e662981c68ba0bd29465f391167de9 reverted (hotfix)

74c2e9020f04b26e7ccf217d956ead740566e991 reverted (hotfix)

04d94e3c092bbbaee5ec1331930b11af58ced629 reverted (hotfix)

538b86bfc640ddcfd4d28b1e2660acdef0ce9b08 reverted (hotfix)

3b8579d8a570eeeaf0d4e0667e748d484df138aa reverted (hotfix)

970c1bc49b804d0b7fa515292f27ac2fb4ef29e8 reverted (hotfix)

f26e0ba212e6164eb7535f472415334d1a9c9044 reverted (hotfix)
automatischer Merge von include/mfidl.idl

bc52edc19d8a45b9062d9568652403251872026e reverted (hotfix)

b3655b5be5f137281e8757db4e6985018b21c296 reverted (hotfix)

95ffc879882fdedaf9fdf40eb1c556a025ae5bfd reverted (hotfix)

0dc309ef6ac54484d92f6558d6ca2f8e50eb28e2 reverted (hotfix)

25948222129fe48ac4c65a4cf093477d19d25f18 reverted (hotfix)

7f481ea05faf02914ecbc1932703e528511cce1a reverted (hotfix)

c45be242e5b6bc0a80796d65716ced8e0bc5fd41 reverted (hotfix)
automatischer Merge von include/mfidl.idl

d5154e7eea70a19fe528f0de6ebac0186651e0f3 reverted (hotfix)

d39747f450ad4356868f46cfda9a870347cce9dd reverted (hotfix)

250f86b02389b2148471ad67bcc0775ff3b2c6ba reverted (hotfix)

40ced5e054d1f16ce47161079c960ac839910cb7 reverted (hotfix)

8bd3c8bf5a9ea4765f791f1f78f60bcf7060eba6 reverted (hotfix)

87e4c289e46701c6f582e95c330eefb6fc5ec68a reverted (hotfix)

51b6d45503e5849f28cce1a9aa9b7d3dba9de0fe reverted (hotfix)

c76418fbfd72e496c800aec28c5a1d713389287f reverted (hotfix)

37e9f0eadae9f62ccae8919a92686695927e9274 reverted (hotfix)
automatischer Merge von dlls/wmvcore/tests/wmvcore.c

dd182a924f89b948010ecc0d79f43aec83adfe65 reverted (hotfix)
automatischer Merge von dlls/wmvcore/tests/wmvcore.c

4f10b95c8355c94e4c6f506322b80be7ae7aa174 reverted (hotfix)
automatischer Merge von dlls/wmvcore/tests/wmvcore.c

4239f2acf77d9eaa8166628d25c1336c1599df33 reverted (hotfix)
automatischer Merge von dlls/wmvcore/tests/wmvcore.c

3dd8eeeebdeec619570c764285bdcae82dee5868 reverted (hotfix)
automatischer Merge von dlls/wmvcore/tests/wmvcore.c

831c6a88aab78db054beb42ca9562146b53963e7 reverted (hotfix)

2d0dc2d47ca6b2d4090dfe32efdba4f695b197ce reverted (hotfix)
Entferne dlls/winegstreamer/wm_reader.c

963589ee296ae90003dab3e8204766ab4e4c0045 reverted (hotfix)

2adf4376d86119b8a6f7cde51c9a972564575bac reverted (hotfix)
automatischer Merge von dlls/winex11.drv/display.c
KONFLIKT (Inhalt): Merge-Konflikt in dlls/winex11.drv/display.c

`

**Comment by gardotd426** [comment] 2021-12-01 10:18
Duplicate of #608

**Closed** 2021-12-02 13:21 UTC
