### ISSUE TITLE
Dependancy conflict arch linux. Wine-tkg wants jack2 but pipewire-jack is installed

### ISSUE THREAD

**Issue by llde** [Frogging-Family/wine-tkg-git#671] opened 2022-01-21 11:09 UTC
Hi. Recently in pipewire based configuration jack2 was replaced with pipewire-jack. however pipewire-jack doesn't provide jack2 in dependancy resolutions as jack2-dbus can't   be used.
If wine doesn't expect the specific jack2 implementation using jack nd lib32-jack as dependancy instead of jack2 and lib32-jack2 can be the solution

**Comment by ninelore** [comment] 2022-01-21 22:42
This is a arch repo issue. You try to uninstall `lib32-jack2` first then you should be able to just replace jack2 with pipewire jack by pacman

**Comment by ninelore** [comment] 2022-01-21 22:43
```
pacman -Rc lib32-jack
pacman -Syu
```

**Comment by llde** [comment] 2022-01-22 00:25
pipewire-jack  provide the jack dependancy BUT NOT the jack2 dependancy that this PKGBUILD use.

**Comment by Mar0xy** [comment] 2022-01-22 07:46
This issue happens cause pipewire-jack recently switched over to jack2 from jack I just went ahead and replaced it for the install/build then redownloaded pipewire-jack

> pipewire-jack provide the jack dependancy BUT NOT the jack2 dependancy that this PKGBUILD use.

yes and that is the issue jack2 and pipewire-jack both provide jack

**Comment by ninelore** [comment] 2022-01-22 13:11
its what Mar0xy said plus with pipewire-jack theres no reason to have `jack2` over `jack` anyway.

Also its still a upstream Arch Problem. If this is still an issue for for some reason open an issue on https://bugs.archlinux.org

/close

**Comment by llde** [comment] 2022-01-22 16:31
someone did open the issue on arch tracker but was closed as "Not a bug". 
Again the point stand this PKGBUILD should rely on jack dependancy not jack2 dependancy. It works.
This is the main point that your comments didn't address. Why? Becouse as the situation stands if I use pipewire-jack I can't install this package. And honestly speaking I don't want to have both a pipewire and an indipendent jack server installed.
So I disagree. This is a valid issue that was triggered by a specific change in the arch repositories: Adding jack2 in the conflicts array without adding it in the provide array. But jack2 cannot be put in provide as some of the very few packages that has an explicit dependancy on jack2  doesn't work with pipewire-jack. (Only jack2-dbus use an explicit dependancy actually)

> its what Mar0xy said plus with pipewire-jack theres no reason to have jack2 over jack anyway.

You are right and this is EXACTLY the problem. WIne-tkg do explicitly link jack2 and lib32-jack2 AND is exactly THIS that is causing a conflict with pipewire-jack. Again wine-tkg should not require explicitly jack2 and lib32-jack2 and should use the more sensible choice of using jack and lib32-jack as dependancies.


@Mar0xy @ninelore

**Comment by ninelore** [comment] 2022-01-22 17:37
It works for me and I use pipewire-jack. wine works with either jack or jack2. As long as you don't actually use jack for its primary purpose (studio-grade music recording and production) you shouldnt care much about which you got installed.

It was closed as not a bug because it isn't. pipewire-jack replaces both jack and jack2 in functionality.

**Comment by llde** [comment] 2022-01-22 18:21
Wine works, but default arch wine and wine-staging don't have jack or jack2 in dependancy. Are you using pipewire-jack with wine-tkg without modifying the PKGBUILDs?
Becouse this PKGBUILD do have jack2 listed as strict dependancy.
And jack2 isn't listed in pipewire-jack provides.
So the only options I can think on why we aren't understanding each others are:
1) You aren't using wine-tkg but default repo wine (or staging)
2) You have a modified version of pipewire-jack (that also provides jack2  explictly). Maybe from a different repository.
3) You are using a modified PKGBUILD for tkg 
4) You have another package that provide a fake jack2 dependancy for resolution.
jack2 provide was removed from the package in the pkgrel=4 rebuild 6 days ago.

**Comment by ninelore** [comment] 2022-01-22 20:33
If you would have done more careful research like 
- reading the PKGBUILDs of both wine-tkg and repo wine 
- reading ``pacman -Si jack` and `pacman -Si jack2`

you would know that 
- `jack2` is a **make**-dependency for both repo wine and wine-tkg
- `jack` provides `jack2` and vice versa

**Comment by llde** [comment] 2022-01-22 20:50
@ninelore 
Where do you see jack2 for wine?
https://github.com/archlinux/svntogit-community/blob/packages/wine/trunk/PKGBUILD
There isn't.
Jack2 provides. jack. pipewire-jack provides jack (not jack2)
Jack doesn't exist anymore as standalone package. Replaced by jack2 or pipewire-jack
Are we looking even at the same distro?
Of course pacman -Si jack doesn't work.
This PKGBUILD strictly link to jack2 as makedepends.
I also read the PKGBUILDs. Both Wine and Wine-Tkg. And they clearly state the same thing I'm saying (while you didn't provide any info, telling me to query a non existant package). 
In my local PKGBUILD I already modified the dependancy to jack and lib32-jack. This issue is to avoid issues to other with pipewire.

 Dio boia.

**Comment by ninelore** [comment] 2022-01-22 20:58
> Where do you see jack2 for wine?
I fail to see where this even matters.

> Jack doesn't exist anymore as standalone package. 
It does. Look it up before you wrint untruth

> This PKGBUILD strictly link to jack2 as makedepends.
There is no strictly. `provides=` is the reason why this is not true. Maybe do some research on the inner working of your distro.

> BTW Your very first comment clearly state that you didn't understand at all what I was trying to report.
I understand very clearly what you want to report because i already said that i **had** the issue myself

> Stating I was trying to uninstall jack2, instead of replacing.
I told you to do that to fix it

**Comment by ninelore** [comment] 2022-01-22 21:08
Edit: mb jack did get moved to the AUR not so long ago

Still: both `pipewire-jack` and `jack` work in building wine-tkg

**Comment by llde** [comment] 2022-01-22 21:11
> I fail to see where this even matters.

Also you the comment before:
> jack2 is a make-dependency for both repo wine and wine-tkg


> There is no strictly. provides= is the reason why this is not true. Maybe do some research on the inner working of your distro.

provides allow a package to make itself visible using that name. In this case it means that both jack2 and pipewire-jack can resolve a "jack" dependancy.  There is no package that provides jack2. So by linking to jack2 you are strictly requiring jack2 to be installed.

> I understand very clearly what you want to report because i already said that i had the issue myself

No you were speaking about a dependancy breaking while uninstalling jack.  You posted the command to remove lib32-jack and remove it's dependancy in cascade.
lib32-jack was already not present in this system. 
This is to show how much you did understand.

> Still: both pipewire-jack and jack work in building wine-tkg

They works certainly. If I skip the dependancy checks.
Still pipewire-jack do provide only jack not jack2 so the dependancy resolver can't honestly succeed.
If it works on your system then you have another package that is providing jack2
Tertium non datur

**Comment by ninelore** [comment] 2022-01-22 21:12
If you insist ill will fix that for you gimme 5 min to make a PR

**Comment by llde** [comment] 2022-01-22 21:14
If I wasn't away from my working computer I would have maked the PR myself. It's honestly a pain to make a test  with this laptop.

**Comment by ninelore** [comment] 2022-01-22 21:25
PR open, sry for misscommunication

**Closed** 2022-01-22 21:34 UTC
