### ISSUE TITLE
proton-tkg makepkg ignores staging_version="5.8"

### ISSUE THREAD

**Issue by CygnusTerminal** [Frogging-Family/wine-tkg-git#151] opened 2020-09-24 14:39 UTC
Hey everyone, i am trying to compile a custom proton-tkg with dxgi support and with Wine staging 5.8. The relevant proton-tkg.cfg looks like this:
# WINE FLAVOUR SETTINGS

_use_esync="true"
_use_fsync="true"

_plain_version=""
_use_staging="true"
_staging_version="5.8"

Is there something wrong? Am i missing something?

**Comment by CygnusTerminal** [comment] 2020-09-24 14:55
-> Cloning and preparing sources... Please be patient.
/home/vektor/wine-tkg-git/wine-tkg-git/wine-tkg-scripts/prepare.sh: line 56: cd: /home/vektor/wine-tkg-git/wine-tkg-git/src/wine-mirror-git: No such file or directory
This error showed when using proton-tkg.sh

**Comment by Tk-Glitch** [comment] 2020-09-24 16:35
> Is there something wrong? Am i missing something?

Staging tags are prefixed with a `v`, so you'll want to use `v5.8` in your case. Mainline tags are as you typed though.
Regarding the issue afterwards, try running `wine-tkg-git/wine-tkg-git/non-makepkg-build.sh` first, then cancel once the clones are done. That should fix it. Also, can I ask which distro is in use?

Thanks

**Comment by CygnusTerminal** [comment] 2020-09-24 17:54
> > Is there something wrong? Am i missing something?
> 
> Staging tags are prefixed with a `v`, so you'll want to use `v5.8` in your case. Mainline tags are as you typed though.
> Regarding the issue afterwards, try running `wine-tkg-git/wine-tkg-git/non-makepkg-build.sh` first, then cancel once the clones are done. That should fix it. Also, can I ask which distro is in use?
> 
> Thanks

Thanks! I forgot to mention i am running vanilla Arch Linux.

**Comment by Tk-Glitch** [comment] 2020-09-25 14:57
The source initialization issue when running proton-tkg directly is still a mystery to me (and I'm unable to reproduce it so far), but the other issue you faced in your edit should now be fixed.

**Comment by CygnusTerminal** [comment] 2020-09-25 19:38
> The source initialization issue when running proton-tkg directly is still a mystery to me (and I'm unable to reproduce it so far), but the other issue you faced in your edit should now be fixed.

Thanks tkg! I was able to compile the package, since the first error was because i was writing "5.8" insteas of "v5.8". When i added the "v", the sources downloaded and the package started compiling.

**Comment by Tk-Glitch** [comment] 2020-09-26 13:02
Great news! Feel free to close the issue if it's all good :)

**Closed** 2020-09-30 01:55 UTC
