### ISSUE TITLE
Automatic CI using wine-tkg-git

### ISSUE THREAD

**Issue by robigan** [Frogging-Family/wine-tkg-git#443] opened 2021-07-06 20:34 UTC
So some members of the grapejuice community (A Roblox on Linux community) including I are seeking to automatically compile wine with patches specific to the Roblox client. And we like using wine-tkg-git to do this since it facilitates the whole process really well, so I wanted to ask if it's possible to supply automatic input to the non-makepkg-build.sh script so we can automate the compile process or should I be doing something else?

**Comment by paulcarroty** [comment] 2021-07-07 13:01
Duplicate of #243

**Closed** 2021-07-12 11:57 UTC
