### ISSUE TITLE
`proton-tkg-steamclient-swap.patch` Fails to Apply to Wine-Staging 8.9.1 Release

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/wine-tkg-git#1030] opened 2023-06-19 18:57 UTC
Wine-Staging Commit: `2dcacd0dbff86e3b6c08e0ecebec96a1be8d7506` (8.9.1 Release)
EDIT: Also affects 8.8 Staging release

<details><summary>prepare.log</summary>

```make
proton-tkg-steamclient-swap.patch -- ( Applied steamclient substitution hack )
patching file dlls/ntdll/loader.c
Hunk #1 succeeded at 4867 (offset 267 lines).
patching file dlls/ntdll/ntdll.spec
Hunk #1 succeeded at 1700 (offset 8 lines).
patching file dlls/ntdll/ntdll_misc.h
Hunk #1 succeeded at 87 (offset 2 lines).
patching file dlls/ntdll/unix/loader.c
Hunk #1 succeeded at 118 (offset 2 lines).
Hunk #2 succeeded at 1861 with fuzz 2 (offset 798 lines).
Hunk #3 succeeded at 2091 (offset -102 lines).
Hunk #4 succeeded at 2113 (offset -104 lines).
patching file dlls/ntdll/loader.c
Hunk #1 succeeded at 91 with fuzz 2 (offset 7 lines).
patching file dlls/ntdll/loader.c
Hunk #1 succeeded at 2244 (offset 244 lines).
Hunk #2 succeeded at 2274 (offset 244 lines).
patching file dlls/ntdll/unix/loader.c
Hunk #1 succeeded at 2057 with fuzz 2.
Hunk #2 FAILED at 2135.
1 out of 2 hunks FAILED -- saving rejects to file dlls/ntdll/unix/loader.c.rej
patching file dlls/ntdll/unix/signal_i386.c
Hunk #1 succeeded at 1883 (offset -4 lines).
Hunk #2 succeeded at 1918 (offset -5 lines).
patching file dlls/ntdll/unix/signal_x86_64.c
Hunk #1 succeeded at 2175 (offset -7 lines).
Hunk #2 succeeded at 2207 (offset -7 lines).
patching file dlls/ntdll/unix/unix_private.h
Hunk #1 succeeded at 224 (offset 29 lines).
patching file dlls/ntdll/unixlib.h
Hunk #1 succeeded at 81 with fuzz 2 (offset 41 lines).
patching file dlls/ntdll/unix/loader.c
patching file dlls/ntdll/unix/loader.c
Hunk #1 succeeded at 733 with fuzz 1 (offset 8 lines).
Hunk #2 succeeded at 739 with fuzz 2 (offset -21 lines).
patching file dlls/ntdll/env.c
Hunk #1 succeeded at 698 (offset 14 lines).
patching file dlls/ntdll/ntdll.spec
Hunk #1 succeeded at 1706 with fuzz 2 (offset 70 lines).
patching file dlls/ntdll/unix/env.c
Hunk #1 succeeded at 2411 with fuzz 2 (offset -205 lines).
patching file dlls/ntdll/unix/loader.c
Hunk #1 FAILED at 2157.
1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/unix/loader.c.rej
patching file dlls/ntdll/unix/unix_private.h
Hunk #1 succeeded at 341 (offset 51 lines).
patching file dlls/ntdll/unixlib.h
Hunk #1 succeeded at 88 (offset 45 lines).
patching file include/wine/debug.h
Hunk #1 succeeded at 114 (offset -35 lines).
patching file dlls/ntdll/unix/env.c
Hunk #1 succeeded at 2414 (offset -206 lines).
patching file programs/winebrowser/main.c
patching file dlls/ntdll/unix/loader.c
Hunk #1 succeeded at 1195 (offset -63 lines).
Hunk #2 succeeded at 1220 (offset -62 lines).
```
</details>

**Comment by Tk-Glitch** [comment] 2023-06-25 15:25
Duplicate of https://github.com/Frogging-Family/wine-tkg-git/issues/1025

**Closed by Tk-Glitch** 2023-06-25 15:25 UTC
