### ISSUE TITLE
Horizon Zero Dawn floating textures

### ISSUE THREAD

**Issue by samxl001** [Frogging-Family/wine-tkg-git#191] opened 2020-10-18 11:16 UTC
I am using proton_tkg_5.19.r1.gb49e8743 to play Horizon Zero Dawn. When I load the game there are many floating textures. Quitting the game and deleting PSOCache.bin sometimes fixes the issue. But most of the time even after deleting the file the floating texture remains.
I am on Manjaro KDE with Nvidia 450.80.02 driver

**Comment by Tk-Glitch** [comment] 2020-10-18 22:11
On Nvidia I'm pretty sure you'll need to update your driver to 455.26.01 or newer. Any 455 series driver *might* be enough, I can't remember.

**Comment by samxl001** [comment] 2020-10-20 11:12
Thanks for the info. Upgrading the driver 455.28 fixed the issue. However, the game hangs up after 30 to 40 mins playtime. Is this an existing issue also?

**Comment by Tk-Glitch** [comment] 2020-10-20 19:56
That's indeed a known issue, which seems to be more frequent on Nvidia. It's pretty random. No real fix as of yet afaik.

**Comment by samxl001** [comment] 2020-10-23 17:11
Thanks for the info. Should I close this issue?

**Comment by Nocifer** [comment] 2020-10-24 09:18
A heads up, as I completed HZD just yesterday: there is kind of a patch available for vkd3d-proton that makes it so the game never ever crashes no matter what (that's how it was for me) or at least doesn't crash for several hours (for some other people). It's posted over at Valve's Proton git, in the [HZD-specific thread](https://github.com/ValveSoftware/Proton/issues/4125#issuecomment-695752992).

Just do as the patch creator @intersectRaven says in the comment I linked, i.e. clone his `personal` branch recursively and build it. Or, if you want the easy mode, just do as I did and clone @Tk-Glitch's dxvk-tools repo, then:

In the file "upvkd3d-proton" replace
`git remote add -t \* -f origin https://github.com/HansKristian-Work/vkd3d-proton`
with
`git remote add -t \* -f origin https://github.com/intersectRaven/vkd3d-proton`

and in the file "upvkd3d-proton.cfg" replace
`VKD3D_PROTON_BRANCH=master`
with
`VKD3D_PROTON_BRANCH=personal`

And then just build it and copy over the resultant d3d12.dll's to their proper places in your wine prefix.

**Comment by intersectRaven** [comment] 2020-10-24 09:56
The real fix for this issue is the latest Vulkan development driver. In the latest 455 official, the barrier fix seems incomplete so it still happens randomly so this issue can be closed as it's a driver issue. As for the post above, my workaround does not address floaties so I don't know why it was mentioned here. Also, there have still been reports of crashes with my workaround. It's just lessened it.

**Comment by Nocifer** [comment] 2020-10-24 13:58
@intersectRaven, the OP's original problem may have been the floating textures, but a couple of comments later they also reported experiencing crashes:

> Thanks for the info. Upgrading the driver 455.28 fixed the issue. **However, the game hangs up after 30 to 40 mins playtime. Is this an existing issue also?**

That's why I mentioned your workaround, not because of the floating textures which are indeed a separate, driver-related issue.

Also FYI, as I've already mentioned in my previous comment, using a d3d12.dll compiled with your workaround enabled me to run HZD for several hours per day across several days without even a single crash, compared to the crashes I was consistently getting every ~15-30 minutes. But even if your workaround does not completely eliminate the crashes (as seems to be the case with other people, which I've also already mentioned in my previous comment) it should at least allow the OP to play the game for at least a couple of hours before getting a crash, which I'd say is much better than "30 to 40 mins of playtime".

Oh and btw, thanks anyway for providing the workaround.

**Comment by Tk-Glitch** [comment] 2020-11-14 22:10
Closing this since the floaties should be fixed - until vkd3d regression :frog:

**Closed by Tk-Glitch** 2020-11-14 22:10 UTC
