### ISSUE TITLE
Proton - Unable to launch game for the second time

### ISSUE THREAD

**Issue by KookiesGH** [Frogging-Family/wine-tkg-git#303] opened 2021-03-22 20:10 UTC
Hello. Having this strange problem using tkg proton on steam: I can launch the game for the first time fine, and everything seems to be set up. However, after trying to launch for a second time, it stops working. Here's my [Proton log](https://github.com/Frogging-Family/wine-tkg-git/files/6185020/steam-704270.log) if it's of any use. Thanks in advance!

**Comment by Tk-Glitch** [comment] 2021-03-23 18:22
It seems to be a common issue which isn't directly related to the wine side of things: https://github.com/ValveSoftware/Proton/issues/4269

**Comment by Tk-Glitch** [comment] 2021-03-23 18:23
It might be worth trying to delete the prefix of the affected game.

**Comment by KookiesGH** [comment] 2021-03-23 19:35
Ah gotcha, that makes sense. I did see [a fix in one of GE's releases](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/6.1-GE-2) that I thought may be related to my problem ("removed previous steam common redistributables fix for winetricks -- it was causing crashes on arch systems, and winetricks fixed the download urls upstream anyway. This should also fix some issues with games launching once then not launching again."). Or I could be completely off, which is usual.

**Comment by Tk-Glitch** [comment] 2021-03-23 21:23
We're not affected by that issue since we never used it in the first place. I also cannot reproduce the issue on my end. If the solder runtime gets in the way for some reason (which doesn't happen for me), this might be a problem. I'd still attempt nuking the affected prefix to see if it fixes the issue.

**Comment by KookiesGH** [comment] 2021-03-24 00:47
Alright, thanks for you help!

**Comment by iWeaker4you** [comment] 2021-04-04 17:20
@Tk-Glitch  In my case it is different, in the first launch, it does not work, it only does not install the requirements of each game, I have to use another version of Proton, such as PROTON GE or Proton Exp for the installation of the requirements such as .net, directx etc etc.

**Comment by iWeaker4you** [comment] 2021-04-04 17:21
[steam-382890.log](https://github.com/Frogging-Family/wine-tkg-git/files/6255014/steam-382890.log)

The interesting thing that it does not generate anything in Proton Log.

**Comment by Tk-Glitch** [comment] 2021-04-04 18:02
Could you try a newer version? 6.5 release is kind of a shitshow.

**Comment by Tk-Glitch** [comment] 2021-06-10 17:01
Should be fixed now, closing

Feel free to report if it isn't.
Also check https://github.com/Frogging-Family/wine-tkg-git/issues/396, which might look similar

**Closed by Tk-Glitch** 2021-06-10 17:01 UTC
Labels: upstream
