### ISSUE TITLE
_NOLIB32="wow64" + _NOMINGW="true" fails on pre build checks

### ISSUE THREAD

**Issue by Gigas002** [Frogging-Family/wine-tkg-git#1277] opened 2024-09-29 14:32 UTC
Can't build after https://github.com/Frogging-Family/wine-tkg-git/commit/de5febaf41a0baa8f577f982f8976b1d07e33e4d with params:

```
_NOLIB32="wow64"
_NOMINGW="true"
```

Fails on pre build checks:

```
checking for i686-w64-mingw32-gcc... no
checking for i586-w64-mingw32-gcc... no
checking for i486-w64-mingw32-gcc... no
checking for i386-w64-mingw32-gcc... no
checking for i686-w64-mingw32-clang... no
checking for i586-w64-mingw32-clang... no
checking for i486-w64-mingw32-clang... no
checking for i386-w64-mingw32-clang... no
checking for clang... clang
checking whether clang supports -target i686-windows -fuse-ld=lld -Wl,-subsystem:console -Wl,-WX --no-default-config... no
checking whether clang supports -target i686-windows -fuse-ld=lld -Wl,-subsystem:console -Wl,-WX... no
checking whether clang works... yes
configure: error: i386 PE cross-compiler not found.
This is an error since --enable-archs=i386 was requested.
```

When `_NOLIB32="true"` or `_NOLIB32="false"` build at least starts

**Comment by Tk-Glitch** [comment] 2024-10-01 03:17
You can't build wow64 wine without mingw, period.
We used to add mingw to dependencies no matter what, but we are now only adding it when `_NOMINGW="false"` (default) as of https://github.com/Frogging-Family/wine-tkg-git/commit/de5febaf41a0baa8f577f982f8976b1d07e33e4d.
So it's all working as intended now. The bug was to grab mingw as dependency when `_NOMINGW="true"` was set, allowing to build wow64 builds while making the user believe it was building without mingw when it's not possible.

Closing.

**Closed by Tk-Glitch** 2024-10-01 03:17 UTC

**Comment by Gigas002** [comment] 2024-10-01 03:20
Ack, thanks for explanation!
