### ISSUE TITLE
ERROR: Patch application has failed on protonified build

### ISSUE THREAD

**Issue by ryanmusante** [Frogging-Family/wine-tkg-git#1062] opened 2023-09-02 02:05 UTC
Build continues to fail, unsure why. 

prepare.log attached
wine-tkg.cfg attached (renamed to txt for github)

```
Cloning into 'wine-git'...
done.
  -> Creating working copy of wine-staging-git git repo...
Cloning into 'wine-staging-git'...
done.
==> Starting prepare()...
  -> 
  -> Changing wine HEAD to the wine-staging base commit...
  -> Using upstream-commit file
HEAD is now at 0cea9c78fa8 Release 8.15.
==> WARNING: fshack (and associated patches) currently disabled until conflicts are resolved
==> WARNING: Hotfix: Fix for Riot Client updates
==> WARNING: Hotfix: Bcrypt fixes for RDR2
==> WARNING: Hotfix: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.
==> WARNING: Hotfix: Fix for CL/opencl.h header recognition
==> WARNING: Hotfix: Fix NosTale mouse bug
  -> cherry picking...
  -> Hotfixing...
  -> Applying CSMT-toggle.patch
  -> Applying wine-staging patches using staging/patchinstall.py... 
     Staging overrides used, if any: 
  -> Applying fsync-unix-staging.patch
  -> Applying server_Abort_waiting_on_a_completion_port_when_closing_it.patch
  -> Applying fsync_futex_waitv.patch
  -> Applying childwindow-proton.patch
  -> Applying OPWR-proton.patch
  -> Applying LAA-unix-staging.patch
  -> Applying proton-tkg-staging.patch
==> ERROR: Patch application has failed. The error was logged to /home/ryan/.cache/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
==> Removing installed dependencies...
```
[prepare.log](https://github.com/Frogging-Family/wine-tkg-git/files/12502503/prepare.log)

[wine-tkg.cfg.txt](https://github.com/Frogging-Family/wine-tkg-git/files/12502614/wine-tkg.cfg.txt)

**Comment by Tk-Glitch** [comment] 2023-09-02 02:06
Duplicate of https://github.com/Frogging-Family/wine-tkg-git/issues/1060

**Closed by Tk-Glitch** 2023-09-02 02:06 UTC
