### ISSUE TITLE
Document changes better

### ISSUE THREAD

**Issue by Thaodan** [Frogging-Family/wine-tkg-git#84] opened 2020-07-11 21:15 UTC
It would be great if changes would be commit in a better cleaner way.
Two examples: you revert some changes on top of wine via an array of git commit hashes, if these hashes would beach on its own line every commit would be better visible when you remove and a new.
The second is that you have large patch on top of wine-staging it would be easier to understand if this was based on multiple patches.

I've had the idea to post this a bit longer but as this package contains fixes that fix WINE#49436 and I couldn't find which I thought I create this issue.

**Comment by Tk-Glitch** [comment] 2020-07-12 01:09
I am fully aware and I agree with you. The "hotfixer" path wasn't supposed to stay awake for that long, and thankfully it's coming to an end. Zebediah might be able to push his esync rebase to staging soon which will free us from this.

The fix for #49436 is kind of a byproduct of the whole mess required to keep esync/fsync working, which basically reverts both offending commits (537bb7a8 and b7ccb9d0).
I initially imported them back (https://github.com/Frogging-Family/wine-tkg-git/commit/329ec17c4f7d6e0cf4e28c217d2bc1ef69c1f672) but got reports of breakage on HotS, followed by Overwatch, which I could reproduce with WoW on my end. So I eventually disabled the importation and let the author of those patches know about it.

**Comment by Thaodan** [comment] 2020-07-12 01:33
Can you comment this on the bug I've cited?

Also it would be great if the pkgbuild would be less interactive by default and use mingw as makedepend for clean chroot builds.

**Comment by Tk-Glitch** [comment] 2020-07-12 02:04
I'd prefer not to comment on the bug just yet as I haven't verified reverting those commits fixes the issue on a clean source. Due to the massive amount of reverts in "hotfixed" trees it's not a valid test case. Unless you have tested reverting those commits on current HEAD (with no other revert or patch) already?

I have a pending AUR PKGBUILD that isn't interactive.
Regarding mingw we have had multiple dependency checks but ultimately,
 - it's a huge and horrendous one
 - it's only available on AUR, which currently offers a build that's broken
 - it's optional

(I'm not counting chaotic-aur in there due to its nature)

So until the situation changes we'll leave mingw handling at the discretion of the builder.

**Comment by Thaodan** [comment] 2020-07-12 02:28
Can you add it as makedepend via an option?

I looked for the two commits and they are not inside the wine where the bug got triggerd for me (https://github.com/wine-staging/wine-staging/commits/9a4c8c5631101f8571dbdce726ae864060e446c9)

**Comment by Tk-Glitch** [comment] 2020-07-12 02:36
I'm pretty sure that one was a different issue that got fixed during the 5.11-devel window. It could be anything at this point considering the huge ntdll refactoring mess and how much of it gets reverted in the hotfixer. So yeah, I won't comment on the issue until I have a clearer picture.

> Can you add it as makedepend via an option?

I'll do better than that! Not before tomorrow though.

**Comment by Thaodan** [comment] 2020-07-12 02:46
I know building mingw is hard because it takes a hole process of building various package in a chain of dependency. I rebuild it just as a test and it builds fine for me.

I commented on the knowledge that I know on the bug at least. I'm not sure where the bug is as I didn't use plain wow for a while. I suspect its plain wine. I think someone should I to revert your commits one by one.

**Comment by Thaodan** [comment] 2020-07-12 02:48
>I'll do better than that! Not before tomorrow though.

Sure do that it is to late already :)

If you want a prebuild mingw look here: https://thaodan.de/public/archlinux/home-thaodan/x86_64/

**Comment by Tk-Glitch** [comment] 2020-07-12 03:02
> I rebuild it just as a test and it builds fine for me.

Oh yeah sorry I wasn't more precise. The breakage is due to the combination with binutils 2.34. It'll create subtle bugs in programs compiled with the toolchain. The problem will be fixed in 2.35 which will land very soon.

See https://github.com/Tk-Glitch/PKGBUILDS/issues/501

I'm using my mostlyportable-gcc script (https://github.com/Frogging-Family/mostlyportable-gcc) to build my gcc/mingw compilers so I don't have to suffer through the random breakages of the AUR and get much more flexibility.

**Comment by Thaodan** [comment] 2020-07-12 03:13
Ah yeah I applied the patch to binutils already.

I prefer to use the packaging system as much as possible for this 
but the script looks like something like this: (which can in turn 
build mingw-w and which I use for hybris)
https://github.com/franzflasch/build-tools-gcc[1] 

--------
[1] https://github.com/franzflasch/build-tools-gcc

**Comment by Tk-Glitch** [comment] 2020-12-13 17:44
We are now freed of the horrible hotfixer path (since 5.20), so let's close.

**Closed by Tk-Glitch** 2020-12-13 17:44 UTC
