### ISSUE TITLE
Performance(?) regression from somewhere between 6.0a and 6.10

### ISSUE THREAD

**Issue by insunaa** [Frogging-Family/wine-tkg-git#407] opened 2021-06-09 06:25 UTC
Playing WoW TBC Classic with dx12 on the latest proton-tkg drastically increases the temperature of my CPU, when compared to proton-tk 6.0a. I have a 5950x and play with vsync, so I don't actually notice any performance difference, but the difference in temperatures is drastic. With 6.0a I'm around ~50-60°C with 30% fanspeed, with 6.10 I'm at 73-78°C at full fan speed.

I'm loading the wine64 binary through lutris, fsync is enabled, esync is disabled. Kernel is 5.12.9-164-tkg-pds

htop doesn't show any noteworthy changes in CPU usage

Edit: OK, aside from lutris just being suboptimal, there are some problems with getting VKD3D to load using this package. I believe to remember that VKD3D was bundled/compiled into the proton wine binary, is this not the case anymore?

Edit2: happens when using the protonified wine build, too. There also seems to be a memory leak?

**Comment by Tk-Glitch** [comment] 2021-06-10 16:47
The regression was spotted by other users but might be kinda by design at this point. We are providing a couple patchsets that should help quite a bit (it did for others), that you can find in the community patches:
https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/0002-proton_LFH.mypatch
https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/0002-proton_QPC.mypatch

> I'm loading the wine64 binary through lutris
> I believe to remember that VKD3D was bundled/compiled into the proton wine binary

That's not exactly true. It's bundled into the proton build, but it'll only get used when using the proton script, which lutris bypasses. Running your game/app with `/path/to/proton/dir/proton run /path/to/game/exe` would work and make use of the proton specifics, including both dxvk and vkd3d-proton.

**Comment by ZeroZXZ** [comment] 2021-06-18 21:19
I also noticed the same performance regression issues, It got to a point my CPU was heating up above 95Cº - 80Cº being highest values and 90 Cº being critical; I tried to do what OP said, and reversed back to Proton 5.8, all games are running fine now.

Even 2D Games like "Megaman Legacy Collection 2" would cause CPU to overheat. So it wasn't just a performance issue, this is affecting hardware as well. I remember I tried switching kernels, setting options on bootloader for it, but nothing. Only reverting back to 5.8 fix'd all the issues.

I would love to know when this get fixed, btw.
so just commenting this over here, btw.

**Comment by ZeroZXZ** [comment] 2021-06-18 21:33
Furtherover, I also noticed by using "powertop" that tick_sched_timer was polling above 800 events/s, hrtimer_wakeup was polling at 400 events/s or so. Both are processes on "Timer Category'. By using htop I would notice that the game would go above >300% of CPU Usage. nvtop(nvidia's htop) would show decreased GPU usage, only using 24% of the GPU, Also low memory usage.

Tried disabling my iGPU (since I own a sandy bridge processor) and games got even slower.
In the end reverting back to 5.8 fix'd everything.

**Comment by ebiroud** [comment] 2021-06-19 15:09
I'd like to also mention that if anyone wonders why [0002-proton_QPC.mypatch ](https://github.com/Frogging-Family/community-patches/blob/master/wine-tkg-git/0002-proton_QPC.mypatch)won't do a thing, won't make any difference, it is probably due to usage of anything else than TSC as clocksource because kernel doesn't trust it. It is also mentioned in one of the commit messages in the patch.

This can be checked by
`cat /sys/devices/system/clocksource/clocksource0/current_clocksource`

It is also my case on Ryzen 7 4800H, so I have to force TSC. I wasn't able to get more than 60 fps on CP77 and GPU usage was below 99% many times, this boosted performance hell of a lot.

If you decide to force TSC, keep in mind kernel doesn't trust it **for a reason**, do it just **on your own risk** with a knowledge of what you are doing and you are fine with issues that can occur!

**Comment by insunaa** [comment] 2021-06-19 21:36
I tried bisecting upstream wine and can confirm that the issue is present in a clean wine 6.10 build, but I can't compile any earlier wine versions, because they're incompatible with GCC11

If anybody has GCC10 and is willing to look into bisecting wine, that'd be greatly appreciated!

**Comment by ZeroZXZ** [comment] 2021-06-21 16:19
Ok, so the problem is fixed by moving from Proton-TKG to Proton-GE, you won't miss a thing from doing this, because Proton-GE is now Upstream, so it will get the most recent wine and proton updates just as TKG has been doing for quite a while now. So ye.

I'm also getting slow downs + CPU Overheat on Epic Store & Epic Store games i've got samsho running at 16FPS and CPU at 100 Cº, the issue is clearly wine, although this has been fix'd in Proton-GE.

So don't wait for a proton-tkg patch anytime soon, hence the QPC and LFH patches did nothing for TKG on my end. My clocksource is already TSC by default, so i don't think that's the only issue here.

**Comment by Tk-Glitch** [comment] 2021-06-22 21:32
Except Proton GE has exactly zero fix for anything of the sort. I can't reproduce such an issue on my end either, as you can see in the attached screenshot - 17% CPU usage and 40C° for the hottest core - and this is on Proton-tkg 6.11. All my games are running fine as usual, too.

![Screenshot_20210622_232326](https://user-images.githubusercontent.com/741977/123001408-fb5fda80-d3b0-11eb-88fc-213487065155.png)

That being said I'm not using Arch's toolchains and I'm building with mostlyportable instead. Considering some talks about Arch's mingw package being broken regarding wine I'm starting to think it might actually be related.

**Comment by insunaa** [comment] 2021-06-23 06:15
Maybe it's an issue that depends on certain hardware?
My CPU is a Ryzen 9 5950X and my GPU is an Nvidia RTX 3080 (proprietary drivers)

**Comment by Tk-Glitch** [comment] 2021-06-25 10:38
Please see: https://github.com/Frogging-Family/wine-tkg-git/issues/427

**Comment by insunaa** [comment] 2021-06-25 10:41
Interesting. Will test around a bit later today, thank you!

**Comment by insunaa** [comment] 2021-06-25 10:59
At least for this particular issue this seems to have done nothing. I'm still getting temperatures that are way higher than they were with previous versions of wine-tkg
In addition to that applications that rely on CEF seem to be stuttering and lagging out a lot when initializing and only recover after ~5-10 seconds, after which they seem to run smoothly. (In my particular test case, the entire Battle.net application didn't really work, it just crybabied about Agent.exe, but that's probably unrelated

**Comment by Tk-Glitch** [comment] 2021-06-25 11:04
Reagarding battle.net, 414b31bc0bbbfe005e90a1946a649082dc303c55 is known to have broken it. You can also revert it cleanly.

**Comment by insunaa** [comment] 2021-06-25 11:15
OK, with both of the reverts in place, the temperature issue is fixed. Battle.net is still kinda broken, but half-way usable and I figure that'll have to be enough.

Thank you for looking into this!

**Comment by SveSop** [comment] 2021-06-25 11:32
@Tk-Glitch 
> That being said I'm not using Arch's toolchains and I'm building with mostlyportable instead. Considering some talks about Arch's mingw package being broken regarding wine I'm starting to think it might actually be related.

Mingw + avx = trouble afaik, and has been for a long time. 
There is some patches for the ubuntu build of gcc-mingw-w64 package ref. [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939559#32](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939559#32) that makes mingw be a bit different than Arch's when it comes to AVX from my testing.

I can build wine ok with ubuntu gcc-mingw-w64 (10.3) package, but i have issues when i build dxvk with that (32-bit games crashing), so i need to build dxvk package with arch docker image atm. Why this is, i dont know, but there is something strange going on at times when it comes to AVX and mingw, even tho i do not use any spesific build options like `-march=native` or anything like that when building dxvk package. If i do that in my arch docker image, dxvk crashes both on -32 or -64 bit... (I7 8700K btw)

Probably not related to this issue tho, but just as a sidenote if you want to dig deeper than my know-how allows. "Build fine" is a relative term ref. bugs like these where SOME systems seems to exhibit weird instability and/or high cpu usage, since for all we know it could be compiler related maybe...

**Comment by SveSop** [comment] 2021-06-25 16:15
https://github.com/Frogging-Family/wine-tkg-git/commit/891d5362ea2dd394cb9cfdd76c7e5608990c0886 seems to fix World of Warcraft retail atleast for now, but the Battle.net app is (as said above) kinda borked.

**Closed** 2021-06-25 18:00 UTC
Labels: upstream

**Comment by ZeroZXZ** [comment] 2021-06-27 00:21
> Except Proton GE has exactly zero fix for anything of the sort. I can't reproduce such an issue on my end either, as you can see in the attached screenshot - 17% CPU usage and 40C° for the hottest core - and this is on Proton-tkg 6.11. All my games are running fine as usual, too. - @Tk-Glitch 

They actually had several performance issues fix'd that were introduced by their old 6.8 and 6.9 Proton-GE versions. 
Source: https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/6.10-GE-1.

I'm avoiding using EpicStore because for same reason: it's being affected by the same regression performance issue. Which is impacting big time on Both performance and CPU Temperature.

Using Proton-GE has fix'd the issue.

**Comment by Tk-Glitch** [comment] 2021-06-27 15:41
> They actually had several performance issues fix'd that were introduced by their old 6.8 and 6.9 Proton-GE versions.
> Source: https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/6.10-GE-1.

You're talking about 6.10, which has far less issues than 6.11. The 6.0-6.10 issue we're talking about here has nothing to do with any of those so called "fixes" in GE.
Things is, we either didn't introduce the issue in -tkg or already had fixes in place. GE even grabbed my patches variants to fix some of those. The networking regression was the only thing we didn't share for a while since I had no issue on my end (while he had). I ended up adding his patch after a few people reported the issue happened for them with -tkg too. However, it reportedly didn't fix any of this on our end unlike openglfreak's patch (added in the commit closing this issue), so I disabled them (GE's patch it was linked to a different regression in 6.10, which didn't affect perf. But since I couldn't reproduce the perf issue, it was impossible to track on my end).

> I'm avoiding using EpicStore because for same reason: it's being affected by the same regression performance issue. Which is impacting big time on Both performance and CPU Temperature.

The regression is upstream and we now have a workaround in place. It was only affecting *some* as I couldn't reproduce the issue at all on my end on any machine, like many other users.

> Using Proton-GE has fix'd the issue.

Well, obviously, a issue introduced with 6.11 issue won't affect 6.10.

**Comment by SveSop** [comment] 2021-06-27 16:33
> 
> The regression is upstream and we now have a workaround in place. It was only affecting _some_ as I couldn't reproduce the issue at all on my end on any machine, like many other users.
> 

Some online games uses some functions that others dont i would say. I mean.. server-sync vs. packet time calculations or whatnot. FPS games tends to utilize different server syncing compared to mmo's for instance. (WoW being kinda notorious for horrible cpu calculations making even the most awesomest RTX3080Ti beast crawl to a halt at times) 
The network regression introduced < 6.9 might not have caused problems for other than a select few types of network code used in games, and thus harder to pinpoint with testing.

I could try to fire up WoW with Proton-GE-6.10, but i need to recreate the prefix since proton is a wee bit whacky compared to wine-staging when setting up overrides and whatnot.. so i would prefer not to. (Does not really matter for now, since the patch from Openglfreak fixes this).
