### ISSUE TITLE
Games not closing properly while using proton-tkg on steam

### ISSUE THREAD

**Issue by adih2001** [Frogging-Family/wine-tkg-git#268] opened 2021-01-20 22:49 UTC
As the title suggests, after I close down a game (from within the game) that was launched from steam, it does appear to close down but the wine proccess still runs and steam shows the game as if it's still running so I have to close it down manually within steam. I have encountered this issue with FFXIV, FFXV Demo, Unreal Tournament 3 and Witcher 3 and they have had this issue.
I do not have this issue with neither proton experimental or proton 5.13-5.
I am using proton-tkg-git-6.0.r2.g6364ada0-1-x86_64, Arch Linux with 5.9.2-94-tkg-upds kernel. As for steam I am using the current latest update that arch has to offer atm.

Here is the config I used to generate proton-tkg if it helps: https://pastebin.com/nGpNmh30

**Comment by Tk-Glitch** [comment] 2021-01-27 15:47
After investigating, the issue is linked to Proton's steam_helper. Something in there breaks when built against recent wine (only tested on staging so far). The weird part is that it's pretty random and doesn't happen with all games.

**Comment by Tk-Glitch** [comment] 2021-06-10 17:07
Fixed. Closing.

**Closed by Tk-Glitch** 2021-06-10 17:07 UTC
Labels: bug
